# Generated by Django 4.0.5 on 2022-06-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_dislikes_dislike_rename_likes_like_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dislike",
            unique_together={("post", "dis_liked_by")},
        ),
    ]
